### ISSUE TITLE
Initial stage scroll collapsed

### ISSUE THREAD

**Issue by enieber** [rgommezz/react-native-scroll-bottom-sheet#15]
### Current Behavior

I create one ScrollBottomSheet with component type ScrollView, the initial state of the scroll is not collapsed.

### Expected Behavior

I like create the ScrollBottomSheet with initial state of scroll is collapsed

### How to reproduce

the sample runnign in snak of expo:

https://snack.expo.io/@enieber/scrollbottomsheet

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.1
| react-native                      | ~0.61.5
| react-native-gesture-handler      | ^1.6.1
| react-native-reanimated           | ~1.7.0
| expo   |  37.0.3

**Comment by rgommezz** [comment]
`initialSnapIndex` should be `2` and not `0`.

They start from the top, as specified in the [docs](https://github.com/rgommezz/react-native-scroll-bottom-sheet#explicit)
