### ISSUE TITLE
Tests failing after installing react-native-scroll-bottom-sheet

### ISSUE THREAD

**Issue by joe-goodall-ticketmaster** [rgommezz/react-native-scroll-bottom-sheet#17]
After installing tests have started failing for some reason?

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.1
| react-native                      | 0.62.2
| react-native-gesture-handler      | 1.5.0
| react-native-reanimated           | 1.8.0

<img width="695" alt="Screenshot 2020-06-19 at 21 06 58" src="https://user-images.githubusercontent.com/65718433/85176648-34cbaa80-b272-11ea-9525-0cc61755e257.png">

Struggling to work out what's going on. Removing `react-native-scroll-bottom-sheet` causes the test to pass again 🤔

**Comment by rgommezz** [comment]
Hi @joe-goodall-ticketmaster,

At first glance, it seems you are not mocking properly either `react-native-gesture-handler` or `react-native-reanimated`.

For reanimated you can mock the module as:

```js
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));
```

For gesture handler, try to follow [this](https://docs.swmansion.com/react-native-gesture-handler/docs/getting-started.html#testing)

**Comment by joe-goodall-ticketmaster** [comment]
Thanks for your quick response @rgommezz,

I'll try that out and let you know 👍

**Comment by joe-goodall-ticketmaster** [comment]
Mocking the `react-native-reanimated` module sorted it 🎉

Thanks for your help @rgommezz.

Apart from this ⬆️ issue, the library was easy to get set up and looks great 👍
