### ISSUE TITLE
[Feature Request] tapper off drag at top / bottom instead of hard stop 

### ISSUE THREAD

**Issue by chrisdrackett** [rgommezz/react-native-scroll-bottom-sheet#2]
### Current Behavior

Right now when the sheet reaches the top of bottom of its range there is a hard stop.

### Expected Behavior

It would be nice to add an option to taper the movement at the edges. Something like how framer motion handles drag when you reach the edges:

https://codesandbox.io/s/day-10-drag-momentum-config-ph8dd

**Comment by rgommezz** [comment]
Hey @chrisdrackett,

You can configure the animation by providing a duration and/or a different easing function, via `animationConfig`. Have you tried [that](https://github.com/rgommezz/react-native-scroll-bottom-sheet#props)?

Some references:
Visualisation of common easing functions: https://easings.net/
Easing options `reanimated` exposes: https://github.com/software-mansion/react-native-reanimated/blob/1701f3947f4f5cf5350203a06c2845c55601c406/src/Easing.js

**Comment by chrisdrackett** [comment]
So I think what I'm looking for has some to do with using a spring (#4) but also the gesture handler. I want to be able to drag a sheet past the end/beginning, but would wan the finger tracking to drop from say 1:1 to 1:4 or similar. Basically past the end it gets "stickier". Then when the user lets go the sheet would snap back to the point in question. Here is a quick video:

https://www.dropbox.com/s/n5ym11fyqix6eu3/RPReplay_Final1590092459.mp4?dl=0

**Comment by rgommezz** [comment]
Ok, I see what you mean.

I see the value on overshooting for spring animations type, but the GH thingy it's not trivial. Let's leave this open for future reference.

In the meantime, if you wanna be able to [approximate the curve to a spring](https://easings.net/#easeOutElastic), you can use:

```ts
animationConfig: {
	easing: Easing.out(Easing.elastic(bounciness))
}
```

[Here is information about `bounciness` value](https://github.com/software-mansion/react-native-reanimated/blob/1701f3947f4f5cf5350203a06c2845c55601c406/src/Easing.js#L138)

**Comment by chrisdrackett** [comment]
The reason a real spring is important is the velocity of the release when dragging needs to be taken into account or the animation won’t feel natural.

**Comment by rgommezz** [comment]
Totally agree, the reason I went for `timing` initially is because it's simpler to implement. 

I'll definitely take a look soon to extend it to spring animations as well.

Stay tuned!

**Comment by chrisdrackett** [comment]
exciting! I'll keep an eye out and I'm going to spend some time learning the internals in case I can be helpful :)

**Comment by djorkaeffalexandre** [comment]
Hey guys! @rgommezz, I would love to see this implemented too. hehe, If I can help please feel free to reach me out, I'm going to study more `react-native-reanimated` to understand the principles.
Thanks in advance.
Djorkaeff.

**Comment by Appkidd** [comment]
Would also love to see this!

**Comment by rgommezz** [comment]
Hey folks, version [v0.7.0](https://github.com/rgommezz/react-native-scroll-bottom-sheet/releases/tag/v0.7.0) has been published, that contains support for spring based animations as well as an optional prop to tapper off the movement at the bottom edge and go beyond the lower snapping point 🙂 

Closing this issue then!

Thanks for your patience

**Comment by Appkidd** [comment]
Excellent news. Thanks @rgommezz!

**Comment by miladdev85** [comment]
@rgommezz Is it possible to fix this somehow for top as well when using spring?
The spring animation has a hard stop at top and does not go beyond the higher snapping point. 

My snap points are: snapPoints={[100, height - 200]} and the lower works great but when it is "expanded" the spring animation has a hard stop and looks weird...

**Comment by ankushShetty1993** [comment]
Just give bounces prop to true.
