### ISSUE TITLE
React Native Paper's List component not working properly in Android

### ISSUE THREAD

**Issue by sorxrob** [rgommezz/react-native-scroll-bottom-sheet#23]
### Current Behavior

I'm trying to use [react-native-paper's](https://github.com/callstack/react-native-paper) `List` component inside the bottom sheet and the behavior in Android is strange. I have to press it longer just to make the ripple appear, and the `onPress` handler doesn't fire.

**iOS**

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/13049130/85218795-2bf0eb00-b3d0-11ea-8a77-5a9fe75f23d6.gif)

**Android**

![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/13049130/85218809-52af2180-b3d0-11ea-87e1-51a0e5cfd36a.gif)

### Expected Behavior

Pressing the `List.Item` will cause the ripple to appear (without long pressing it) and fire the `onPress` event handler.

### How to reproduce

Snack: https://snack.expo.io/@wobsoriano/react-native-paper-with-bottom-sheet

1. Clicking an item should show a timestamp below the `Appbar`
2. Pressing an item should make the ripple appear.

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.1
| react-native                      | 37.0.1
| react-native-gesture-handler      |  1.6.0
| react-native-reanimated           | 1.7.0

This project really rocks btw 👊🏿

**Observation:** Actually, all clickable items like the react native paper's `Button` inside the bottom sheet doesn't fire the `onPress` event in Android.

**Comment by rgommezz** [comment]
Hi @sorxrob,

That's expected, due to a limitation on `react-native-gesture-handler`, which this library uses behind the scenes.

Please refer to [this section in the docs](https://github.com/rgommezz/react-native-scroll-bottom-sheet#touchables) for some workarounds.

**Comment by sorxrob** [comment]
> Hi @sorxrob,
> 
> That's expected, due to a limitation on `react-native-gesture-handler`, which this library uses behind the scenes.
> 
> Please refer to [this section in the docs](https://github.com/rgommezz/react-native-scroll-bottom-sheet#touchables) for some workarounds.

Thanks. Do I have to make changes with `react-native-paper's` components?
