### ISSUE TITLE
SegmentedControl ignores touch events

### ISSUE THREAD

**Issue by Appkidd** [rgommezz/react-native-scroll-bottom-sheet#25]
This is a truly great package for scrollable bottom sheets. Would really appreciate any help with this bug.

### Current Behavior

[SegmentedControl](https://github.com/react-native-community/segmented-control) does not update when pressed.

### Expected Behavior

When I touch the SegmentedControl it should update. It responds to `onTouchStart` but it seems like the actual `onChange` event is consumed and therefore doesn't update. Buttons and Touchables seem to work fine, not sure why the same doesn't apply to SegmentedControl.

### How to reproduce

- Add a SegentedControl anywhere inside ScrollBottomSheet and try to select another value.

![screenshot](https://i.imgur.com/TyOR9UA.jpg)

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.2
| react-native                      | 0.62.2
| react-native-gesture-handler      | 1.6.1
| react-native-reanimated           | 1.9.0

**Comment by Appkidd** [comment]
I've noticed that if I press the segmented control with two fingers it works perfectly. I assume this is something to do with the with how gesture handlers have been implemented? Any help would be much appreciated @rgommezz.

**Comment by rgommezz** [comment]
Hey @Appkidd,

I am gonna assume that's happening on Android?

Yes, you are correct. I just took a quick look at the Segmented Control library and they use `TouchableOpacity` behind the scenes, which is based on the JS responder and hence won't work with this library. This [table](https://github.com/rgommezz/react-native-scroll-bottom-sheet#compatibility-table) should help you to address the issue. Essentially, you need the touchables to come from `react-native-gesture-handler` library.

You can use [patch-package](https://github.com/ds300/patch-package) to quickly patch the library and avoid a fork, if you really need that component.

Hope that helps!

**Comment by Appkidd** [comment]
Hey!

It's happening on iOS - sorry I should have been clearer. 😞

**Comment by Appkidd** [comment]
@rgommezz Are you able to take another look at all? We really need to use this library with BottomSheet. TouchableOpacity works fine inside BottomSheet but for some reason the SegmentedControl library doesn't at all. Any help would be super appreciated!

**Comment by Appkidd** [comment]
Setting `maxDurationMs` on the root `TapGestureHandler` fixed the issue. Unsure if this will cause any further issues, but at this stage everything seems to be working as expected.
