### ISSUE TITLE
FlatList scrolling with pan gesture not working properly

### ISSUE THREAD

**Issue by FRizzonelli** [rgommezz/react-native-scroll-bottom-sheet#28]
Hello @rgommezz first of all, I'd like to thank you for the awesome package :)

### Current Behavior

Currently, I'm not able to scroll the bottom sheet with the pan gesture over the flatlist
If I drag the _handle_ everything works fine, problem is I'd like to reproduce the behaviour of your SectionList example but I don't understand what I'm missing.
This is a GIF of my current behaviour:
![mlem](https://user-images.githubusercontent.com/12106217/87295444-7b28c800-c505-11ea-83e5-e899bb72be92.gif)

### Expected Behavior

I'd like to reproduce the behaviour of your example, I tried to download it and run it with expo on iOS simulator, and the animation "jumps" after I start dragging, release the gesture, when I tap again the bottom sheet jumps to the expected position

### How to reproduce

I have this structure to wrap a react-native storybook

```ts
    <>
      <BottomSheetContext.Provider value={{ openBottomSheet, closeBottomSheet, renderHandle }}>
        {children}
        {isVisible && !!bottomSheetProps && (
          <>
            <TouchableWithoutFeedback onPress={closeBottomSheet}>
              <AnimatedBackground style={{ opacity }} />
            </TouchableWithoutFeedback>
            <ScrollBottomSheet<any>
              {...bottomSheetProps}
              ref={bottomSheetRef}
              onSettle={handleSnapPointChanged}
              animatedPosition={animatedPosition.current}
              animationConfig={{
                duration: 150
              }}
              contentContainerStyle={{
                backgroundColor: Colors.WHITE_100
              }}
            />
          </>
        )}
      </BottomSheetContext.Provider>
    </>
```

If I give _contentContainerStyle_ prop a value of flex:1, it works but the flatlist stops scrolling when I reach the top (like setting flex 1 on a normal FlatList).

Any idea?

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.2
| react-native                      | 61.5
| react-native-gesture-handler      | 1.6.1
| react-native-reanimated           | 1.7.1

**Comment by FRizzonelli** [comment]
@rgommezz I've updated my project to latest expo (I was on 37, 38 was released 10ish days ago) and now it's working super smoothly. Probably there is something weird in RN prior 62. Can you try your example on 0.61 and confirm it?

**Comment by rgommezz** [comment]
Hi @FRizzonelli, I never experienced any performance issue on my examples with Expo, on `v37.x`, both Android and iOS (real devices). Maybe it could be a simulator issue.

Happy to see that the upgrade fixed it for you. I am gonna close it for now, but feel free to re-open if it happens again and I'll take a closer look.
