### ISSUE TITLE
Render only handle initially?

### ISSUE THREAD

**Issue by peterzernia** [rgommezz/react-native-scroll-bottom-sheet#3]
### Current Behavior
I'm using this to render a scrollview. It is not consistently showing the height of the handle as a snap point. Using `height (screen) - 50`, the height of the screen - the handle, shows nothing, and bumping it up to higher shows various amounts of the handle and content, and it varies across android and ios

### Expected Behavior

I'd expect screen height - height of handle would just render the handle

### How to reproduce

```
<ScrollBottomSheet
  componentType="ScrollView"
  snapPoints={[128, '50%', height - 50]} // 50 is height of handle
  initialSnapIndex={2}
  renderHandle={() => (
    <View
      style={{
        backgroundColor: 'white',
        borderBottomWidth: 0.1,
        height: 50,
        flexDirection: 'row',
        justifyContent: 'center',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: -10,
        },
        shadowOpacity: 0.1,
        shadowRadius: 5.0,
        elevation: 16,
      }}
    >
      <View style={{
        width: 22,
        height: 4,
        backgroundColor: '#BDBDBD',
        borderRadius: 4,
        marginTop: 17,
      }}
      />
    </View>
  )}
>
  // I don't want any of this view shown initially
  <View
    style={{ backgroundColor: 'red, height: 1000 }}
  />
</ScrollBottomSheet>
```

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  | 0.6.0
| react-native                      | expo 37 - 0.6.0
| react-native-gesture-handler      | 1.6.0
| react-native-reanimated           | 1.7.0

**Comment by rgommezz** [comment]
You need to use `topInset` prop as well, so that you account for the height of status bar, navigation headers and/or notches. Please take a look at the [full description](https://github.com/rgommezz/react-native-scroll-bottom-sheet#explicit) of `snapPoints` prop, where that's explained.

**Comment by peterzernia** [comment]
Thanks! `windowHeight - headerHeight - 50` gave me the expected result
