### ISSUE TITLE
TouchableItem does not accept first press on android

### ISSUE THREAD

**Issue by Quadriphobs1** [rgommezz/react-native-scroll-bottom-sheet#32]
### Current Behavior
Using the Flatlist BottomSheet... TouchableItem doesn't accept onPress event at the first press on android with `react-native-gesture-handler` `TouchableOpacity` component

### Expected Behavior

Should accept onPress event when pressed

### How to reproduce

- You must provide a way to reproduce the problem.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app, with as many details as possible.

### Your Environment

| package                           | version
| ----------------                  | -------
| react-native-scroll-bottom-sheet  |
| react-native                      | 0.63
| react-native-gesture-handler      | ^1.6.1
| react-native-reanimated           | ^1.9.0

**Comment by rgommezz** [comment]
Hey @Quadriphobs1, I've tried to reproduce your issue in the example folder without success. Below is my test case and the alert fired per press as expected.

```ts
import { Alert, Text } from 'react-native';
import { TouchableOpacity } from 'react-native-gesture-handler';

const Transaction = React.memo(
  ({ title, subtitle, amount, iconColor }: ListItemData) => (
    <TouchableOpacity onPress={() => Alert.alert('hello')}>
      <List.Item
        title={title}
        description={subtitle}
        left={props => <List.Icon {...props} icon="folder" color={iconColor} />}
        right={() => (
          <Text style={{ alignSelf: 'center', marginRight: 8 }}>{amount}</Text>
        )}
      />
    </TouchableOpacity>
  ),
  () => true
);
```

Please next time do provide a reproducible case via snack or separate repository, otherwise it's impossible for me to debug properly.
