### ISSUE TITLE
Remove 1px border under the handle

### ISSUE THREAD

**Issue by AronBe** [rgommezz/react-native-scroll-bottom-sheet#51]
I am using `renderHandle` prop to show the handle, under which is 1px border set. How could I please remove it? The only solution I came up with is to move the renderHandle component by `top: 1`, which is not the greatest solution I assume?

![image](https://user-images.githubusercontent.com/32416348/94286433-47324000-ff55-11ea-9d33-15427e129b43.png)

**Comment by BCarroll524** [comment]
If you are rendering a custom JSX.Element in the `renderHandle` prop you can set its style to have a `borderBottomWidth` of `0px` to get rid of the border under the handle.

It could look like the following

```
renderHandle={() => <View style={{ borderBottomWidth: 0 }}> // rest of custom handle </View> }
```

**Comment by AronBe** [comment]
Oh that simple, I though I have tried that, but seems like I failed somewhere :) thank you!

**Comment by AronBe** [comment]
@BCarroll524 I thought it works, but now I am finding out this solution does not work actually. Neither I see any styles for the border used in the code. It is probably some positioning within the code and the only solution is `top: 1`?

**Comment by rgommezz** [comment]
Check the example of the [map screen](https://github.com/rgommezz/react-native-scroll-bottom-sheet/blob/master/example/screens/HorizontalFlatListExample.tsx), where the handle presents no border.

This library does not render any borders, you have full control on the `handle` component
