### ISSUE TITLE
TouchableOpacity onPress is called after a delay

### ISSUE THREAD

**Issue by hasnaina-entertainer** [rgommezz/react-native-scroll-bottom-sheet#57]
### Current Behavior

I am using code as mentioned in readme
const BottomSheetTouchable = (props) => {
  if (Platform.OS === "android") {
    return (
      <RNGHTouchableOpacity {...props} />
    );
  }

  return <TouchableOpacity {...props} />
};

### Expected Behavior

The clicks are working fine except that there is a noticable delay. I am navigating to a new screen on tap of an item in list, and the response is very slow.
### How to reproduce
Click TouchableOpacity inside BottomSheet

### Your Environment

|                                   | version
| ----------------                  | -------
| Platform (Android, iOS or both)   | both
| react-native-scroll-bottom-sheet   |"^0.7.0"
| react-native        | "0.63.3"   
| react-native-gesture-handler    | "^1.8.0"  
| react-native-reanimated      |  "^1.13.1",

**Comment by rgommezz** [comment]
Hey @hasnaina-entertainer,

That's probably related to some performance issues in your React components setup. Unfortunately, this is outside of the scope of this library
