### ISSUE TITLE
Fixed bottom component

### ISSUE THREAD

**Issue by GiorgioBertolotti** [rgommezz/react-native-scroll-bottom-sheet#63]
Hello, is there any way to achieve a design like the one below?
Basically what I need is a button fixed to the bottom of the FlatList.

![Schermata 2021-02-22 alle 17 00 18](https://user-images.githubusercontent.com/15264288/108734281-9c3ba780-752f-11eb-80a5-14f1bac3f02b.png)

**Comment by rgommezz** [comment]
Hey @GiorgioBertolotti,

You'd have to play with `position: absolute` and `zIndex` attributes.

The button would have to be a sibling of the `BottomSheet` component in order to keep it outside the scroll area, something like the below:

```js

<View style={{flex: 1}}>
  <ScrollBottomSheet {...} />
  <View style={{position: 'absolute', bottom: 0, left: 0, right: 0 }}>
    <Button>Anulla</Button>
  </View>
</View>
```

Closing this since it's outside the scope of the library.
